#  请保存为UTF-8格式
spring:
  profiles: prod     #生产环境
  application: 
    name: spring-config-prod
---
spring:
  profiles: dev     #开发环境
  application: 
    name: spring-config-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: spring-config-test
